server:
  port: ${SERVER_PORT}

jwt:
  access-token:
    expiration: 3600  # a day (60 * 60)
  refresh-token:
    expiration: 1209600  # 14 days (14 * 24 * 60 * 60)

admin:
  master-token: ${ADMIN_MASTER_TOKEN}  # 개발용 고정 토큰
  token:
    identifier: ${ADMIN_TOKEN_IDENTIFIER}  # 관리자 식별자
  session:
    expiration: 3600  # 60분 (60 * 60)
    max-concurrent: 1  # 관리자는 1개 세션만

encryption:
  field:
    secret-key: ${ENCRYPTION_SECRET_KEY}


redis:
  expiration:
    refresh-token: 1209600  # 14 days (14 * 24 * 60 * 60)
    kakao-tid: 180  # 3 hours (3 * 60)
    user-session: 3600  # a day
    verification-code: 300  # 5 mins


spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/factory
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update

  properties:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true
